version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    stdin_open: true 
    tty: true