version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - library-db-data:/var/lib/postgresql/data
  app:
    container_name: app
    build: .
    ports:
      - 80:8000
    restart: always
    depends_on:
      - db

volumes:
  db-data:
    name: library-db-data