version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    container_name: app
    command: sh -c "python manage.py makemigrations & python manage.py migrate & python manage.py createsuperuser --noinput & python manage.py runserver 0.0.0.0:8000"
    build: .
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

volumes:
  db-data:
    name: library-db-data